version: '3'

services:
  web:
    build: .
    command: gunicorn wsgi:app -b 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  services:
    build: .
    command: celery -A lend worker -B
    env_file:
      - .env
    volumes:
      - .:/services
    depends_on:
      - redis

  redis:
    container_name: tb-redis
    image: "redis:latest"
    ports:
      - "6389:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: