version: '3'

services:
  redis:
    container_name: tb-redis
    image: "redis:latest"
    ports:
      - "6389:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data: