version: '3'

services:
  web:
    build: .
    command: gunicorn wsgi:app -b 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - APP_BACKEND_URL=web:8000
      - APP_FRONTEND_PORT=3000
    depends_on:
      - web
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/src

  services:
    build: .
    command: celery -A lend worker -B
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    container_name: tb-redis
    image: "redis:latest"
    ports:
      - "6389:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: